service: custom-url
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  environment:
    TABLE_NAME: ${env.URL_SHORTNER_TABLE_ARN}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "${env:URL_SHORTNER_TABLE_ARN}"

plugins:
  - serverless-offline
  - serverless-plugin-typescript

functions:
  mapUrl:
    handler: src/handler.mapUrl
    events:
      - http:
          path: /t/{url}
          method: GET

  setCustomUrl:
    handler: src/handler.setCustomUrl
    events:
      - http:
          path: /shorten-url
          method: POST
    
  logUrlHit:
    handler: src/logsHandler.logUrlHit
    events:
      - http:
          path: /log/{url}
          method: POST
  
  allUrls:
    handler: src/handler.allUrls
    events:
      - http:
          path: /all-urls
          method: GET