service: custom-url
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: dev
  environment:
    MONGODB_URL: ${env:MONGODB_URL}
    COOKIE_ACCESS_TOKEN: ${env:COOKIE_ACCESS_TOKEN}
    DYNAMO_TABLE_NAME: ${env:DYNAMO_TABLE_NAME}
    ALLOWED_ORIGINS: ${env:ALLOWED_ORIGINS}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:UpdateItem
        - dynamodb:Scan
      Resource: "${env:URL_SHORTNER_TABLE_ARN}"

plugins:
  - serverless-offline
  - serverless-plugin-typescript

functions:
  mapUrl:
    handler: src/handler.mapUrl
    events:
      - http:
          path: /t/{url}
          method: GET
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - key
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Origin
            allowCredentials: false

  setCustomUrl:
    handler: src/handler.setCustomUrl
    events:
      - http:
          path: /shorten-url
          method: POST
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - key
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Origin
            allowCredentials: false
  
  allUrls:
    handler: src/handler.allUrls
    events:
      - http:
          path: /all-urls
          method: GET
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - key
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Origin
            allowCredentials: false

  deleteUrl:
    handler: src/handler.deleteUrl
    events:
      - http:
          path: /url
          method: DELETE
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - key
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Origin
            allowCredentials: false

  setUrlNames:
    handler: src/mongoHandler.setUrlNames
    events:
      - http:
          path: /set-url-names
          method: POST
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - key
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Origin
            allowCredentials: false
  
  logUrlHit:
    handler: src/mongoHandler.logUrlHit
    events:
      - http:
          path: /log/{url}
          method: POST
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - key
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Origin
            allowCredentials: false

  userAcessLogs:
    handler: src/mongoHandler.userAccessLogs
    events:
      - http:
          path: /user-access-logs
          method: GET
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - key
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Origin
            allowCredentials: false
custom:
  # serverless offline plugin setup
  serverless-offline:
    httpPort: 5000
