service: custom-url
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  environment:
    MONGODB_URL: ${env:MONGODB_URL}
    COOKIE_ACCESS_TOKEN: ${env:COOKIE_ACCESS_TOKEN}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:UpdateItem
        - dynamodb:Scan
      Resource: "${env:URL_SHORTNER_TABLE_ARN}"

plugins:
  - serverless-offline
  - serverless-plugin-typescript

functions:
  mapUrl:
    handler: src/handler.mapUrl
    events:
      - http:
          path: /t/{url}
          method: GET

  setCustomUrl:
    handler: src/handler.setCustomUrl
    events:
      - http:
          path: /shorten-url
          method: POST
  
  allUrls:
    handler: src/handler.allUrls
    events:
      - http:
          path: /all-urls
          method: GET

  deleteUrl:
    handler: src/handler.deleteUrl
    events:
      - http:
          path: /url
          method: DELETE
  
  logUrlHit:
    handler: src/mongoHandler.logUrlHit
    events:
      - http:
          path: /log/{url}
          method: POST

  userAcessLogs:
    handler: src/mongoHandler.userAccessLogs
    events:
      - http:
          path: /user-access-logs
          method: GET