service: custom-url
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
      Resource: "${env:URL_SHORTNER_TABLE_ARN}"

plugins:
  - serverless-offline
  - serverless-plugin-typescript

functions:
  hello:
    handler: myService/handler.hello
    events:
      - http:
          path: /hello
          method: GET
  mapUrl:
    handler: src/index.mapUrl
    events:
      - http:
          path: /t/{url}
          method: GET